# Generated by Django 4.0.5 on 2022-06-14 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='re_User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=255)),
                ('alternatePhone', models.CharField(max_length=255)),
                ('pan', models.CharField(max_length=255)),
                ('aadhar', models.CharField(max_length=255)),
                ('createDate', models.CharField(max_length=255)),
                ('userType', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
